SourseCode/App/Controllers/ContractController.cs
using Common;
using CRM.BLL;
using CRM.DAL;
using CRM.IBLL;
using Models;
using NPOI.HSSF.UserModel;
using NPOI.SS.UserModel;
using NPOI.XSSF.UserModel;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace CRM.App.Controllers
{
    /// <summary>
    /// Name:合同列表
    /// Author：Jonny
    /// Date:2015-6-17
    /// </summary>
    [SupportFilter]
    public class ContractController : BaseController
    {

        IBLL.ITBContractBLL m_BLL;
        CRM.IBLL.ITBCustomerBLL m_CustomerBLL = new TBCustomerBLL();
        ValidationErrors validationErrors = new ValidationErrors();
        public ContractController()
            : this(new TBContractBLL()) { }
        public ContractController(TBContractBLL bll)
        {
            m_BLL = bll;
        }

        //
        // GET: /Contract/
        public ActionResult Index()
        {
            var PersonList = new SysPersonBLL().GetPersonVisibility(GetCurrentPersonID());
            if (PersonList.Count > 0 && PersonList.Count < 15)
            {
                ViewBag.PersonList = new SelectList(PersonList, "SysPersonID", "SysPersonName");
            }



            return View();
        }

        public ActionResult OfferIndex()
        {
            var PersonList = new SysPersonBLL().GetPersonVisibility(GetCurrentPersonID());
            if (PersonList.Count > 0 && PersonList.Count < 15)
            {
                ViewBag.PersonList = new SelectList(PersonList, "SysPersonID", "SysPersonName");
            }
            return View();
        }

        public ActionResult BridgeIndex()
        {
            var PersonList = new SysPersonBLL().GetPersonVisibility(GetCurrentPersonID());
            if (PersonList.Count > 0 && PersonList.Count < 15)
            {
                ViewBag.PersonList = new SelectList(PersonList, "SysPersonID", "SysPersonName");
            }
            return View();
        }



        /// <summary>
        /// 新增合同
        /// </summary>
        /// <returns></returns>
        public ActionResult CreateContractInfo()
        {
            return View();
        }

        /// <summary>
        /// 新增合同
        /// </summary>
        /// <returns></returns>
        public ActionResult OfferCreateContractInfo(string customerId)
        {
            TB_Contract entity = new TB_Contract();
            if (!string.IsNullOrWhiteSpace(customerId))
            {
                TB_Customer customer = m_CustomerBLL.GetById(customerId);
                if (customer != null)
                {
                    entity.CustomerID = customerId;
                    entity.CustomerName = customer.CustomerName;
                    return View(entity);
                }
            }
            return View(entity);
        }

        /// <summary>
        /// 新增合同
        /// </summary>
        /// <returns></returns>
        public ActionResult BridgeCreateContractInfo(string customerId)
        {
            TB_Contract entity = new TB_Contract();
            if (!string.IsNullOrWhiteSpace(customerId))
            {
                TB_Customer customer = m_CustomerBLL.GetById(customerId);
                if (customer != null)
                {

                    entity.CustomerID = customerId;
                    entity.CustomerName = customer.CustomerName;
                    return View(entity);
                }
            }
            return View(entity);
        }


        #region ==下拉框==
        /// <summary>
        /// 下拉框
        /// </summary>
        /// <param name="type">0:省1:市2:区3:薪酬</param>
        /// <param name="parm"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult GetCombox(int type, string parm)
        {
            IQueryable jsonInfo = m_BLL.GetCombox(type, parm);
            return Json(jsonInfo, "text/html", JsonRequestBehavior.AllowGet);

        }

        #endregion



        /// <summary>
        /// 合同签订保存
        /// </summary>
        /// <param name="companyName"></param>
        /// <param name="companyCode"></param>
        /// <param name="cityCode"></param>
        /// <param name="cityName"></param>
        /// <param name="packages"></param>
        /// <param name="beginDate"></param>
        /// <param name="endDate"></param>
        /// <param name="packageMoney"></param>
        /// <param name="uploadPackage"></param>
        /// <returns></returns>
        public ActionResult AddPackageInfo(string companyName, string companyCode, string cityCode, string cityName, string packages, string beginDate, string endDate, string packageMoney, string uploadPackage)
        {
            Account account = GetCurrentAccount();
            bool isUpdate = m_BLL.AddPackageInfo(companyName, companyCode, cityCode, cityName, packages, beginDate, endDate, packageMoney, uploadPackage, account.Id);
            return Json(new { IsSuccess = isUpdate });
        }
        /// <summary>
        /// Check公司是否已经签合同
        /// </summary>
        /// <param name="companyCode"></param>
        /// <returns></returns>
        public ActionResult CheckCompanyContract(string companyCode)
        {
            bool isUpdate = m_BLL.CheckCompanyContract(companyCode);
            return Json(new { IsSuccess = isUpdate });
        }

        /// <summary>
        /// 合同列表
        /// </summary>
        /// <param name="page">页码</param>
        /// <param name="rows">每页显示的行数</param>
        /// <param name="order">排序字段</param>
        /// <param name="sort">升序asc（默认）还是降序desc</param>
        /// <param name="search">查询条件</param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult GetData(string id, int page, int rows, string order, string sort, string search)
        {

            int total = 0;
            Account account = GetCurrentAccount();
            List<ContractEntity> queryData;
            queryData = m_BLL.GetContractData(account.Id, id, order, sort, search, page, rows, "", ref total);
            return Json(new datagrid
            {
                total = total,
                rows = queryData
            }, JsonRequestBehavior.AllowGet);

        }
        /// <summary>
        /// OFFER合同列表
        /// </summary>
        /// <param name="page">页码</param>
        /// <param name="rows">每页显示的行数</param>
        /// <param name="order">排序字段</param>
        /// <param name="sort">升序asc（默认）还是降序desc</param>
        /// <param name="search">查询条件</param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult offerList(string id, int page, int rows, string order, string sort, string search)
        {

            int total = 0;
            Account account = GetCurrentAccount();
            List<ContractEntity> queryData;
            queryData = m_BLL.GetContractData(account.Id, id, order, sort, search, page, rows, "offer", ref total);
            return Json(new datagrid
            {
                total = total,
                rows = queryData
            }, JsonRequestBehavior.AllowGet);

        }
        /// <summary>
        /// Bridge合同列表
        /// </summary>
        /// <param name="page">页码</param>
        /// <param name="rows">每页显示的行数</param>
        /// <param name="order">排序字段</param>
        /// <param name="sort">升序asc（默认）还是降序desc</param>
        /// <param name="search">查询条件</param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult BridgeList(string id, int page, int rows, string order, string sort, string search)
        {

            int total = 0;
            Account account = GetCurrentAccount();
            List<ContractEntity> queryData;
            queryData = m_BLL.GetContractData(account.Id, id, order, sort, search, page, rows, "Bridge", ref total);
            return Json(new datagrid
            {
                total = total,
                rows = queryData
            }, JsonRequestBehavior.AllowGet);

        }

        #region ==导出==
        /// <summary>
        ///  导出Excle /*在6.0版本中 新增*/
        /// </summary>
        /// <param name="param">Flexigrid传过到后台的参数</param>
        /// <returns></returns>      
        [HttpPost]
        public ActionResult Export(string search)
        {
            string[] titles = { "合同编号", "公司名称", "所在城市", "合同金额", "购买服务", "开单人", "生效日期", "截止日期" };
            string[] fields = { "ContractID", "CustomerName", "CityName", "ContractMoney", "PackageName", "CreatedBy", "EffectiveDate", "Deadline" };
            string sortName = "ContractID";
            string sortOrder = "desc";
            string cid = "";
            string parm = "";
            if (!string.IsNullOrEmpty(search))
            {
                cid = search.Split('&')[0].ToString();
                parm = search.Split('&')[1].ToString();
            }
            Account account = GetCurrentAccount();
            List<ContractModel> queryData = m_BLL.ExportInfo(account.Id, sortOrder, sortName, cid, parm);

            return Content(WriteExcle(titles, fields, queryData.ToArray()));
        }
        #endregion

        #region  创建合同（新增跟进记录合同阶段）   create by chand 2016-09-20
        //
        [SupportFilter]
        public ActionResult Create(string customerId)
        {
            ViewBag.CustomerID = customerId;
            return View();
        }
        [SupportFilter]
        public ActionResult CreateMultiple(string customerId)
        {
            ViewBag.CustomerID = customerId;
            return View();
        }
        [HttpPost]
        [SupportFilter]
        public ActionResult Create(string id, TB_Contract model)
        {
            if (model != null && ModelState.IsValid)
            {
                string currentPerson = GetCurrentPersonID();

                DateTime date = DateTime.Now;
                model.ContractID = Result.GetNewId();

                model.Flag = 1;
                model.VersionNo = 1;

SourseCode/App/Views/Contract/BridgeCreateContractInfo.cshtml
@using Common
@using Models
@model CRM.DAL.TB_Contract

@{ Layout = "~/Views/Shared/Index.cshtml"; }
<style>
    .textbox-text {
        width: 290px;
    }
    .editor-field {
        width: auto;
    }
</style>
<form id="myForm">
    <div class="easyui-layout" title="" style="width:620px">
        <div style="padding: 10px 0px;">
            <div class="editor-label">
                <span class="red">*</span>
                客户名称:@Html.HiddenFor(model => model.ContractType, new { Value = "Bridge" })
            </div>
            <div class="editor-field" style="width:auto;">
                <input type="text" class="textbox-text textbox-text-readonly" id="CustomerName" name="CustomerName" required="required" readonly="readonly" value="@Model.CustomerName" />
                <input type="hidden" id="CustomerID" name="CustomerID" value="@Model.CustomerID" />
                <a class="easyui-linkbutton" href="javascript:void(0)" onclick="ShowCustomer();">选择</a>
            </div>
            <br style="clear: both;" />
            <div class="editor-label">
                <span class="red">*</span>
                签约公司:
            </div>
            <div class="editor-field" style="width:auto;">
                <input id="cbxSigningCompany" name="cbxSigningCompany" style="width: 290px" />
                <input type="hidden" id="SigningCompany" name="SigningCompany" />
            </div>
            <br style="clear: both;" />
            <div class="editor-label">
                <span class="red">*</span>
                服务类型:
            </div>
            <div class="editor-field" style="width:350px; height:auto">
                @Html.CheckBoxListFor(model => model.RecommendSolutionID, Models.SysFieldModels.GetSysFieldByParentIDByNew("1508071046119479968e30ccf1f9f", "Bridge", 2))
                <input type="hidden" id="RecommendSolutionIDs" name="RecommendSolutionIDs" />
            </div>
            <br style="clear: both;" />
            <div class="editor-label">
                <span class="red">*</span>
                合同编号:
            </div>
            <div class="editor-field">
                <input type="text" class="textbox-text" id="ContractNO" name="ContractNO" value="" readonly="readonly" />
            </div>

            <br style="clear: both;" />
            <div class="editor-label">
                <span class="red">*</span>合同金额:
            </div>
            <div class="editor-field">
                <input type="text" class="textbox-text" id="ContractMoney" name="ContractMoney" value="" required="required" />
            </div>
            <br style="clear: both;" />
            <div class="editor-label">
                <span class="red">*</span>付款方式:
            </div>
            <div class="editor-field">
                <input type="text" class="textbox-text" id="PayType" name="PayType" value="" required="required" />
            </div>
            <br style="clear: both;" />
            <div class="editor-label">
                <span class="red">*</span>签约类型:
            </div>
            <div class="editor-field">
                <input type="radio" name="IsNew" value="0" checked="checked"><span>新签</span><input type="radio" name="IsNew" value="1"><span>续签</span>
            </div>
            <br style="clear: both;" />
            <div class="editor-label">
                <span class="red">*</span>生效日期:
            </div>
            <div class="editor-field">
                <input type="text" class="textbox-text" id="EffectiveDate" name="EffectiveDate" required="required" onclick="WdatePicker({ maxDate: '#F{$dp.$D(\'Deadline\');}', dateFmt: 'yyyy-MM-dd' })" style="width:130px" />
            </div>
            <div class="editor-label">
                <span class="red">*</span>截止日期:
            </div>
            <div class="editor-field">
                <input type="text" class="textbox-text" id="Deadline" name="Deadline" value="" required="required" onclick="WdatePicker({ minDate: '#F{$dp.$D(\'EffectiveDate\');}', dateFmt: 'yyyy-MM-dd' })" style="width:130px" />
            </div>
            <br style="clear: both;" />
            <div class="editor-label">
                备注:
            </div>
            <div class="editor-field" style="height: auto">
                <textarea id="Remark" name="Remark" style="width: 290px; height: 53px; resize: none;" maxlength="100" onkeyup="checkLength(this);"></textarea>
                <span style="display: block">您可输入剩余字数：<b class="red" id="leave_letter">100</b></span>
            </div>

            @*<br style="clear: both;" />
                <div class="editor-label">
                    客服:
                </div>
                <div class="editor-field">
                    <input id="selPerson" class="easyui-combobox" name="language" data-options="multiple:true, multiline:true, method:'post',valueField:'SysPersonID',textField:'SysPersonName', panelHeight:'auto'  ">
                    <input type="hidden" id="SysPersonID" name="SysPersonID" />
                    <input type="hidden" id="SysPersonIDOld" name="SysPersonIDOld" />
                </div>*@
            <br style="clear: both;" />
            <br style="clear: both;" />
            <div data-options="region:'south',border:false" style="text-align: center; padding: 5px 5px 5px 0;">
                <input class="a2 f2" type="submit" id="submit" value="创建" style="display:none" />
                <a class="easyui-linkbutton" id="ContactSave" data-options="iconCls:'icon-ok'" href="javascript:void(0)"
                   onclick="SubmitFunc();">保存</a>
                &nbsp; &nbsp; &nbsp;
                <a class="easyui-linkbutton" data-options="iconCls:'icon-cancel'" href="javascript:void(0)"
                   onclick="closeWindow();">取消</a>
            </div>
        </div>
    </div>
</form>
<link href="~/Res/PublicCommon.css" rel="stylesheet" />
<script type="text/javascript">$.getScript("/Scripts/Contract/Create.js")</script>
<script type="text/javascript">

    $(function () {
        $('#selPerson').combobox({
            url: '/SysRole/GetKeFuPerson',
            formatter: function (row) {
                return '<span class="l-btn-left l-btn-icon-left"><span class="l-btn-text">' + row.SysPersonName + '</span></span>';
            },
            onLoadSuccess: function () {
            },
            onSelect: function (row) {
                var newSysOperationId = $("#SysPersonID").val();
                $("#SysPersonID").val(newSysOperationId + (newSysOperationId.length > 0 ? "^" : "") + row.SysPersonID + "&" + row.SysPersonName);
            },
            onUnselect: function (row) {
                var newSysOperationId = $("#SysPersonID").val();
                var delVal = row.SysPersonID + "&" + row.SysPersonName;
                if (newSysOperationId.indexOf("^" + delVal) >= 0)
                    newSysOperationId = newSysOperationId.replace("^" + delVal, "");
                else if (newSysOperationId.indexOf(delVal + "^") >= 0)
                    newSysOperationId = newSysOperationId.replace(delVal + "^", "");
                else
                    newSysOperationId = newSysOperationId.replace(delVal, "");
                $("#SysPersonID").val(newSysOperationId);
            }
        });
    });

    $('#cbxSigningCompany').combobox({
        required: true,
        url: '/SysField/GetComboBoxListByNew?ParentID=1604121151490315992e569f90a1e&&type=Bridge',
        valueField: 'Value',
        textField: 'Text',
        //editable: false
        filter: function (q, row) { //q：文本框内你输入的值，row：列表数据集合；
            var opts = $(this).combobox('options');

            //统一转换成小写进行比较；==0：匹配首位，>=0：匹配任意位置；
            return row[opts.textField].indexOf(q) >= 0;
        },
        onSelect: function (newValue, oldValue) {
            $("#SigningCompany").val(newValue.Value);
        }
    });


    var validator = $("#myForm").validate({
        errorElement: 'span',
        errorClass: 'field-validation-error',
        focusInvalid: false,
        rules: {
            CustomerName: {
                required: true,
            },
            RecommendSolutionID: {
                required: true,
            },
            ContractNO: {
                required: true,
            },
            PayType: {
                required: true,
            },
            ContractMoney: {
                required: true,
            },
            EffectiveDate: {
                required: true,
            },
            Deadline: {
                required: true,
            },
        },

        messages: {
            CustomerName: {
                required: "请选择客户",
            },
            RecommendSolutionID: {
                required: "请选择服务类型",
            },
            ContractNO: {
                required: "请重新选择服务类型",
            },
            ContractMoney: {
                required: "请输入合同金额",
            },
           
            PayType: {
                required: "请输入付款方式",
            },
            EffectiveDate: {
                required: "请选择生效日期",
            },
            Deadline: {
                required: "请选择截止日期",
            },
        },

        invalidHandler: function (event, validator) { //display error alert on form submit
            $('.alert-danger', $('.login-form')).show();
        },

        highlight: function (e) {
            //移除当前控件后面所有元素

            $(e).closest('.editor-field input').addClass('input-validation-error');
        },

        success: function (e) {
            //移除当前控件后面所有元素
            //$(e).removeClass('input-validation-error');
            //$(e).closest('.editor-field').find("input").removeClass('input-validation-error');
            $(e).prev("input").removeClass('input-validation-error');
            $(e).remove();
        },

        errorPlacement: function (error, element) {
            if (element.is(':checkbox') || element.is(':radio')) {
                var controls = element.closest('div[class*="col-"]');
                if (controls.find(':checkbox,:radio').length > 1) controls.append(error);
                else error.insertAfter(element.nextAll('.lbl:eq(0)').eq(0));
            }
            else if (element.is('.select2')) {
                error.insertAfter(element.siblings('[class*="select2-container"]:eq(0)'));
            }
            else if (element.is('.chosen-select')) {
                error.insertAfter(element.siblings('[class*="chosen-container"]:eq(0)'));
            }
            else error.insertAfter(element);

        },

        submitHandler: function (form) {
        },
        invalidHandler: function (form) {
        }
    });

    /************************************************创建会员***********************************************/

    var SubmitFunc = function () {

        var ids = "";
        $("input[name='RecommendSolutionID']:checked").each(function () {
            ids += $(this).val() + ",";
        });
        $("#RecommendSolutionIDs").val(ids);


        var SubmitResult = true;
        // 检测表单是否验证通过 并进行表单验证
        var validateState = $("#myForm").valid();
        if ($("#SigningCompany").val() == "") {
            validateState = false;
        }
        if (!validateState) {
            return false;
        }
        var CustomerID = $("#CustomerID").val();
        $.ajax({
            url: "/Contract/GetRatingScore",
            data: { id: CustomerID },
            type: "post",
            datatype: "json",
            success: function (data) {
                if (data.Result == "") {
                    $.messager.alert("提示", "请完善客户基本信息，才能创建合同！", "info");
                    return false;
                }
                else {
                    $.ajax({
                        url: "/Contract/Create",
                        type: "Post",
                        data: $("#myForm").serialize(),
                        dataType: "json",
                        success: function (data) {
                            if ($.messager) {
                                $.messager.alert('操作提示', data, "info", function (r) {
                                    closeWindow();
                                });
                            }
                        },
                        error: function () {
                            SubmitResult = false;
                        }
                    });
                }
            }
        });
        return SubmitResult;
    };
    function ShowCustomer() {
        showWindow("选择客户", "/Customer/SelectedList?type=contract", 450, 410);
    }
    function checkLength(obj) {
        var maxChars = $(obj).attr("maxlength");
        if ($(obj).val().length > maxChars)
            $(obj).val($(obj).val().substring(0, maxChars));
        var curr = maxChars - $(obj).val().length;
        $("#leave_letter").text(curr.toString());
    }
</script> 

SourseCode/App/Views/Contract/BridgeIndex.cshtml
@using Common
@using Models
@model CRM.DAL.TB_Contract

@{ Layout = "~/Views/Shared/Index.cshtml"; }

<div id="divQuery">
    <div class="easyui-panel" title="查询栏" iconcls="icon-search" collapsible="true" data-options="collapsed:false" style="height:auto;width:auto">
        <table id="ttSearch" class="record" border="0" cellpadding="0" cellspacing="0">
            <tr>
                <th style="width:120px; text-align:right; padding-right:10px;height:36px">查询条件:</th>
                <td>
                    <input id="CustomerName" name="CustomerName" maxlength="100" value="" type="text" placeholder="搜索公司名称" style="width:220px" />
                </td>
            </tr>
            <tr>
                <th style="width:120px; text-align:right; padding-right:10px;height:26px">
                    日期:
                </th>
                <td>
                    <input type="text" id="StartDate" value="@DateTime.Now.AddDays(-7).ToString("yyyy-MM-dd")" onclick="WdatePicker({ maxDate: '#F{$dp.$D(\'EndDate\');}', dateFmt: 'yyyy-MM-dd' })" />
                    <span>到</span>
                    <input type="text" id="EndDate" value="@DateTime.Now.ToString("yyyy-MM-dd")" onclick="WdatePicker({ minDate: '#F{$dp.$D(\'StartDate\');}', dateFmt: 'yyyy-MM-dd' })" />

                </td>
            </tr>
            <tr>
                <th style="width:120px; text-align:right; padding-right:10px;height:26px">
                    服务类型:
                </th>
                <td>
                    @Html.CheckBoxListFor(model => model.RecommendSolutionID, Models.SysFieldModels.GetSysFieldByParentIDByNew("1508071046119479968e30ccf1f9f", "Bridge", 2))
                </td>
            </tr>
            <tr>
                <td colspan="2" style="text-align:center">
                    <a href="#" onclick="flexiQuery()" class="easyui-linkbutton" data-options="iconCls:'icon-search'">
                        查 询
                    </a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                </td>
            </tr>
        </table>

    </div>
</div>
<br style="clear: both;" />
<table id="flexigridData"></table>


<link href="~/Res/PublicCommon.css" rel="stylesheet" />
<script src="/Scripts/Contract/BridgeIndex.js" type="text/javascript"></script>
<link href="~/Content/Contract/Index.css" rel="stylesheet" />

SourseCode/App/Views/Contract/Create.cshtml
@using Common
@using Models
@model CRM.DAL.TB_Contract

@{
    Layout = "~/Views/Shared/Index.cshtml";
}

<div class="easyui-tabs" style="width:100%;height:650px">
    <div title="欧孚合同" style="padding:1px">
        @*@{Html.RenderAction("OfferCreateContractInfo", "Contract");}*@
        <iframe src="/Contract/OfferCreateContractInfo?customerId=@ViewBag.CustomerID" frameborder="0" scrolling="no" style="width: 99%; height: 98%;"></iframe>

    </div>
    <div title="博尔捷合同" style="padding:1px">
        @*@{Html.RenderAction("BridgeCreateContractInfo", "Contract");}*@
        <iframe src="/Contract/BridgeCreateContractInfo?customerId=@ViewBag.CustomerID" frameborder="0" scrolling="no" style="width: 99%; height: 98%;"></iframe>
    </div>
</div>

SourseCode/App/Views/Contract/CreateNew.cshtml
@using Common
@using Models
@model CRM.DAL.TB_Contract

@{
    Layout = "~/Views/Shared/CloseDialog.cshtml";
}
<style>
     
    input  {
        width: 240px;
    }
</style>
 


    <div class="easyui-layout" title=""  >
        <div style="padding: 10px 20px 20px 20px; ">
            <br style="clear: both;" />
            <div class="editor-label">
                <span class="red">*</span>
                合同编号:
            </div>
            <div class="editor-field">
                <input type="text" name="ContractNO" id="ContractNO" value="@ViewBag.MaxContractNO"  readonly="readonly" disabled="disabled"/>
            </div>
            <br style="clear: both;" />
            <div class="editor-label">
                <span class="red">*</span>
                客户名称:
            </div>
            <div class="editor-field">
                <input type="text" name="CustomerName" id="CustomerName" value="" />
            </div>

            <br style="clear: both;" />
            <br style="clear: both;" />
            <div data-options="region:'south',border:false" style="text-align: center; padding: 5px 5px 5px 0;">
                <a class="easyui-linkbutton" id="ContactSave" data-options="iconCls:'icon-ok'" href="javascript:void(0)"
                   onclick="javascript:checkSubmit();">保存</a>
                &nbsp; &nbsp; &nbsp;
                <a class="easyui-linkbutton" data-options="iconCls:'icon-cancel'" href="javascript:void(0)"
                   onclick="closeWindow();">取消</a>
            </div>
        </div>
    </div>

 
<link href="~/Res/PublicCommon.css" rel="stylesheet" /> 

<script type="text/javascript">
    function checkSubmit() {
        var CustomerName = $("#CustomerName").val();
        var ContractNO = $("#ContractNO").val();
        if (CustomerName == "") {

            $.messager.alert('操作提示', '客户名称不能为空', 'error');
        }
        if (CustomerName.lenth < 5) {

            $.messager.alert('操作提示', '客户名称长度不符', 'error');
        }
        $.ajax({
            url: "/Contract/GetCreateNew",
            data: { CustomerName: CustomerName, ContractNO: ContractNO },
            type: "post",
            datatype: "json",
            success: function (data) {

                $.messager.alert('操作提示', data, "info", function (r) {
                    parent.$('#flexigridData').datagrid("reload");
                    parent.$('#flexigridData').datagrid('unselectAll');
                    closeWindow();

                });

            }


        });
    }

</script>

SourseCode/App/Views/Contract/ImportByService.cshtml
@{
    ViewBag.Title = "合同导入";
    Layout = "~/Views/Shared/Index.cshtml";
}
<div class="loadingDiv" style="display: none">
    &nbsp;<img src="../images/loading.gif" alt="Loading" />&nbsp;加载中...
</div>
<div>
    @using (Html.BeginForm("UploadContractData", "Contract", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        <table id="ttSearch" class="record">
            <tr>
                <th>导入模版下载</th>
                <td>
                    <a href="/Contract/DownTemplate" class="easyui-linkbutton" data-options="iconCls:'icon-add'">模板下载</a>
                </td>
            </tr>
            <tr>
                <th>导入</th>
                <td>
                    <input type="file" name="file" id="FileUpLoad1" accept="application/vnd.ms-excel" style="width: 480px;" />
                </td>
            </tr>
            <tr>
                <td colspan="2" style="text-align: center">
                    <input id="ButtonUpload" type="submit" onclick="return checkType();" value="确认导入" class="easyui-linkbutton" style="width: 80px; height: 40px;" />&nbsp; &nbsp;&nbsp; &nbsp;
                    <a class="easyui-linkbutton" iconcls="icon-cancel" style="width: 80px; height: 40px;" onclick="parent.$('#w_import').window('close')"> 关闭</a>
                </td>
            </tr>

        </table>
    }
</div>
<link href="~/Res/PublicCommon.css" rel="stylesheet" />
<script src="~/Scripts/jquery.watermark.min.js"></script>
<script src="~/Scripts/jquery.bpopup-0.7.0.min.js"></script>
<script src="~/Scripts/type-bpopup_fuc.js" type="text/javascript"></script>
<script type="text/javascript">

    function checkType() {

        $(".loadingDiv").show();
        $("#ButtonUpload").attr("disabled", "disabled");
        //得到上传文件的值
        var fileName = document.getElementById("FileUpLoad1").value;
        //返回String对象中子字符串最后出现的位置.
        var seat = fileName.lastIndexOf(".");
        //返回位于String对象中指定位置的子字符串并转换为小写.
        var extension = fileName.substring(seat).toLowerCase();
        debugger;
        //判断允许上传的文件格式
        //var allowed=[".jpg",".gif",".png",".bmp",".jpeg"];
        var allowed = [".xls", ".xlsx"];
        for (var i = 0; i < allowed.length; i++) {
            if (!(allowed[i] != extension)) {
                return true;
            }
        }
        $.messager.alert('提示', "不支持" + extension + "格式", "error");
        $("#ButtonUpload").removeAttr("disabled");
        $(".loadingDiv").hide();
        return false;
    }
</script>